create sequence "public"."comics_id_seq";

create sequence "public"."panels_id_seq";

create table "public"."comics" (
    "id" integer not null default nextval('comics_id_seq'::regclass),
    "date" date not null,
    "title" text not null
);


create table "public"."panels" (
    "id" integer not null default nextval('panels_id_seq'::regclass),
    "comic_id" integer,
    "sentence" text not null,
    "image_url" text not null,
    "panel_order" integer not null
);


create table "public"."story" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "story" text
);


alter table "public"."story" enable row level security;

alter sequence "public"."comics_id_seq" owned by "public"."comics"."id";

alter sequence "public"."panels_id_seq" owned by "public"."panels"."id";

CREATE UNIQUE INDEX comics_pkey ON public.comics USING btree (id);

CREATE UNIQUE INDEX panels_comic_id_panel_order_key ON public.panels USING btree (comic_id, panel_order);

CREATE UNIQUE INDEX panels_pkey ON public.panels USING btree (id);

CREATE UNIQUE INDEX story_pkey ON public.story USING btree (id);

alter table "public"."comics" add constraint "comics_pkey" PRIMARY KEY using index "comics_pkey";

alter table "public"."panels" add constraint "panels_pkey" PRIMARY KEY using index "panels_pkey";

alter table "public"."story" add constraint "story_pkey" PRIMARY KEY using index "story_pkey";

alter table "public"."panels" add constraint "panels_comic_id_fkey" FOREIGN KEY (comic_id) REFERENCES comics(id) ON DELETE CASCADE not valid;

alter table "public"."panels" validate constraint "panels_comic_id_fkey";

alter table "public"."panels" add constraint "panels_comic_id_panel_order_key" UNIQUE using index "panels_comic_id_panel_order_key";

grant delete on table "public"."comics" to "anon";

grant insert on table "public"."comics" to "anon";

grant references on table "public"."comics" to "anon";

grant select on table "public"."comics" to "anon";

grant trigger on table "public"."comics" to "anon";

grant truncate on table "public"."comics" to "anon";

grant update on table "public"."comics" to "anon";

grant delete on table "public"."comics" to "authenticated";

grant insert on table "public"."comics" to "authenticated";

grant references on table "public"."comics" to "authenticated";

grant select on table "public"."comics" to "authenticated";

grant trigger on table "public"."comics" to "authenticated";

grant truncate on table "public"."comics" to "authenticated";

grant update on table "public"."comics" to "authenticated";

grant delete on table "public"."comics" to "service_role";

grant insert on table "public"."comics" to "service_role";

grant references on table "public"."comics" to "service_role";

grant select on table "public"."comics" to "service_role";

grant trigger on table "public"."comics" to "service_role";

grant truncate on table "public"."comics" to "service_role";

grant update on table "public"."comics" to "service_role";

grant delete on table "public"."panels" to "anon";

grant insert on table "public"."panels" to "anon";

grant references on table "public"."panels" to "anon";

grant select on table "public"."panels" to "anon";

grant trigger on table "public"."panels" to "anon";

grant truncate on table "public"."panels" to "anon";

grant update on table "public"."panels" to "anon";

grant delete on table "public"."panels" to "authenticated";

grant insert on table "public"."panels" to "authenticated";

grant references on table "public"."panels" to "authenticated";

grant select on table "public"."panels" to "authenticated";

grant trigger on table "public"."panels" to "authenticated";

grant truncate on table "public"."panels" to "authenticated";

grant update on table "public"."panels" to "authenticated";

grant delete on table "public"."panels" to "service_role";

grant insert on table "public"."panels" to "service_role";

grant references on table "public"."panels" to "service_role";

grant select on table "public"."panels" to "service_role";

grant trigger on table "public"."panels" to "service_role";

grant truncate on table "public"."panels" to "service_role";

grant update on table "public"."panels" to "service_role";

grant delete on table "public"."story" to "anon";

grant insert on table "public"."story" to "anon";

grant references on table "public"."story" to "anon";

grant select on table "public"."story" to "anon";

grant trigger on table "public"."story" to "anon";

grant truncate on table "public"."story" to "anon";

grant update on table "public"."story" to "anon";

grant delete on table "public"."story" to "authenticated";

grant insert on table "public"."story" to "authenticated";

grant references on table "public"."story" to "authenticated";

grant select on table "public"."story" to "authenticated";

grant trigger on table "public"."story" to "authenticated";

grant truncate on table "public"."story" to "authenticated";

grant update on table "public"."story" to "authenticated";

grant delete on table "public"."story" to "service_role";

grant insert on table "public"."story" to "service_role";

grant references on table "public"."story" to "service_role";

grant select on table "public"."story" to "service_role";

grant trigger on table "public"."story" to "service_role";

grant truncate on table "public"."story" to "service_role";

grant update on table "public"."story" to "service_role";


